### ISSUE TITLE
Compile error on OpenWrt platform

### ISSUE THREAD

**Issue by WFANG12719** [m-grant-prg/dnsmasq-logrotate#1]
Hi, Mark, I do really like this tool and try to use it on my openwrt device. However, seems this tools is not designed for openwrt, the compile error msg is:
➜  dnsmasq-logrotate-1.0.13 autoreconf -if
aclocal: warning: couldn't open directory 'm4': No such file or directory
Can't load '/usr/lib/perl5/5.28/auto/attributes/attributes.so' for module attributes: Error relocating /usr/lib/perl5/5.28/auto/attributes/attributes.so: PL_stack_max: symbol not found at /usr/lib/perl5/5.28/XSLoader.pm line 87.
 at /usr/lib/perl5/5.28/attributes.pm line 112.
Compilation failed in require at /usr/lib/perl5/5.28/Thread/Queue.pm line 17.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.28/Thread/Queue.pm line 17.
Compilation failed in require at /usr/bin/automake line 55.
BEGIN failed--compilation aborted at /usr/bin/automake line 58.
autoreconf: error: automake failed with exit status: 2

I confirmed I have both M4 and Perl5.28 installed on Openwrt router.
My device hardware is ARM v8 : 
#opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10
# uname -a
Linux 5.15.13 #37 SMP PREEMPT Wed Jan 5 22:29:01 CST 2022 aarch64 GNU/Linux

Hope this tool can support Openwrt, as dnsmasq is a must on almost all openwrt devices.

**Comment by m-grant-prg** [comment]
Hi,
This looks like 2 problems:-

1) The warning "aclocal: warning: couldn't open directory 'm4': No such file or directory" is unexpected but just a warning and can be safely ignored.
2) Can't load "'/usr/lib/perl5/5.28/auto/attributes/attributes.so' for module attributes:" etc. This looks like a Perl installation issue. I'm afraid I don't know Perl and never realised that autoreconf used it. However, searching on the web I did find the following:-
[https://forums.cpanel.net/threads/perl-related-issue.660777/](url)
Although it refers to a different module it looks remarkably similar. Maybe you could check. (Unless you were using root I would suggest checking your login account ~/.bashrc

**Comment by m-grant-prg** [comment]
Sorry messed up the link. This should work.

[Cannot load](https://forums.cpanel.net/threads/perl-related-issue.660777/)
